#	MakeFile	-  Make instructions for assembly language examples.
#
#	Copyright Apple Computer, Inc. 1986-1987
#	All rights reserved.
#
#	This makefile builds:
#		The sample application: 		Sample
#		The sample MPW Tool:			Count
#		The sample desk accessory:		Memory
#

Sample			ƒƒ	Sample.r
	Rez Sample.r -o Sample -append
	SetFile -a B Sample -c ASMP -t APPL		# set the bundle bit
Sample			ƒƒ	Sample.a.o
	Link Sample.a.o -o Sample
Sample.a.o		ƒ	Sample.a
	Asm Sample.a


Count			ƒƒ	Count.r
	Rez Count.r -o Count -append
Count			ƒƒ	Count.a.o Stubs.a.o
	Link -w -c 'MPS ' -t MPST Count.a.o Stubs.a.o ∂
		-sn INTENV=Main ∂
		-sn %A5Init=Main ∂
		"{Libraries}"Runtime.o ∂
		"{Libraries}"ToolLibs.o ∂
		-o Count
Count.a.o		ƒ	Count.a
	Asm Count.a
Stubs.a.o		ƒ	Stubs.a
	Asm Stubs.a


Memory			ƒ	Memory.a.o
	Link -da -t DFIL -c DMOV -rt DRVR=12 -sg Memory ∂
		Memory.a.o -o Memory
Memory.a.o		ƒ	Memory.a
	Asm Memory.a
