#	File MakeFile -  Make instructions for C examples.
#
#	Copyright Apple Computer, Inc. 1986-1988
#	All rights reserved.
#
#	This makefile builds:
#		The sample C tool:				Count
#		The sample desk accessory:		Memory
#		The sample performance tool:	TestPerf
#

Count			ƒƒ	Count.r
	Rez Count.r -o Count -append
Count			ƒƒ	Count.c.o FStubs.c.o
	Link -w -c 'MPS ' -t MPST Count.c.o FStubs.c.o ∂
		-sn STDIO=Main ∂
		-sn INTENV=Main ∂
		-sn %A5Init=Main ∂
		"{Libraries}"Stubs.o ∂
		"{CLibraries}"CRuntime.o ∂
		"{CLibraries}"StdCLib.o ∂
		"{CLibraries}"CInterface.o ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"ToolLibs.o ∂
		-o Count
Count.c.o		ƒ	Count.c
	C Count.c
FStubs.c.o		ƒ	FStubs.c
	C FStubs.c



Memory			ƒ	Memory.DRVW Memory.r
	Rez -rd -c DMOV -t DFIL Memory.r -o Memory
Memory.DRVW 	ƒ	Memory.c.o
	Link -w -rt DRVW=0 ∂
		-sg Memory ∂
		"{Libraries}"DRVRRuntime.o	# This must preceed CRuntime.o ∂
		Memory.c.o ∂
		"{CLibraries}"CRuntime.o ∂
		"{Libraries}"Interface.o ∂
		-o Memory.DRVW -c "????" -t "????"
Memory.c.o		ƒ	Memory.c
	C Memory.c



TestPerf	ƒ	TestPerf.c.o
	Link -d # suppress duplicate warnings ∂
		-o TestPerf -t MPST -c 'MPS ' ∂
		-l -la > TestPerf.map # produce link map file ∂
		TestPerf.c.o "{Libraries}"PerformLib.o ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"Runtime.o ∂
		"{CLibraries}"CRuntime.o ∂
		"{CLibraries}"StdCLib.o
TestPerf.c.o	ƒ	TestPerf.c
	C TestPerf.c
