/*
	File:		AERegistry.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __AEREGISTRY__
#define __AEREGISTRY__

#ifndef __TYPES__
#include <Types.h>
/*	#include <ConditionalMacros.h>								*/
/*	#include <MixedMode.h>										*/
/*		#include <Traps.h>										*/
#endif

#ifndef __APPLEEVENTS__
#include <AppleEvents.h>
/*	#include <Memory.h>											*/
/*	#include <OSUtils.h>										*/
/*	#include <Events.h>											*/
/*		#include <Quickdraw.h>									*/
/*			#include <QuickdrawText.h>							*/
/*				#include <IntlResources.h>						*/
/*	#include <EPPC.h>											*/
/*		#include <PPCToolBox.h>									*/
/*			#include <AppleTalk.h>								*/
/*		#include <Processes.h>									*/
/*			#include <Files.h>									*/
/*				#include <SegLoad.h>							*/
/*	#include <Notification.h>									*/
#endif

enum  {
	cAEList						= 0x6c697374,					//  'list'  //
	cApplication				= 0x63617070,					//  'capp'  //
	cArc						= 0x63617263,					//  'carc'  //
	cBoolean					= 0x626f6f6c,					//  'bool'  //
	cCell						= 0x6363656c,					//  'ccel'  //
	cChar						= 0x63686120,					//  'cha '  //
	cColorTable					= 0x636c7274,					//  'clrt'  //
	cColumn						= 0x63636f6c,					//  'ccol'  //
	cDocument					= 0x646f6375,					//  'docu'  //
	cDrawingArea				= 0x63647277,					//  'cdrw'  //
	cEnumeration				= 0x656e756d,					//  'enum'  //
	cFile						= 0x66696c65,					//  'file'  //
	cFixed						= 0x66697864,					//  'fixd'  //
	cFixedPoint					= 0x66706e74,					//  'fpnt'  //
	cFixedRectangle				= 0x66726374,					//  'frct'  //
	cGraphicLine				= 0x676c696e,					//  'glin'  //
	cGraphicObject				= 0x63676f62,					//  'cgob'  //
	cGraphicShape				= 0x63677368,					//  'cgsh'  //
	cGraphicText				= 0x63677478,					//  'cgtx'  //
	cGroupedGraphic				= 0x63706963					//  'cpic'  //
};

enum  {
	cInsertionLoc				= 0x696e736c,					//  'insl'  //
	cInsertionPoint				= 0x63696e73,					//  'cins'  //
	cIntlText					= 0x69747874,					//  'itxt'  //
	cIntlWritingCode			= 0x696e746c,					//  'intl'  //
	cItem						= 0x6369746d,					//  'citm'  //
	cLine						= 0x636c696e,					//  'clin'  //
	cLongDateTime				= 0x6c647420,					//  'ldt '  //
	cLongFixed					= 0x6c667864,					//  'lfxd'  //
	cLongFixedPoint				= 0x6c667074,					//  'lfpt'  //
	cLongFixedRectangle			= 0x6c667263,					//  'lfrc'  //
	cLongInteger				= 0x6c6f6e67,					//  'long'  //
	cLongPoint					= 0x6c706e74,					//  'lpnt'  //
	cLongRectangle				= 0x6c726374,					//  'lrct'  //
	cMachineLoc					= 0x6d4c6f63,					//  'mLoc'  //
	cMenu						= 0x636d6e75,					//  'cmnu'  //
	cMenuItem					= 0x636d656e,					//  'cmen'  //
	cObject						= 0x636f626a,					//  'cobj'  //
	cObjectSpecifier			= 0x6f626a20,					//  'obj '  //
	cOpenableObject				= 0x636f6f62,					//  'coob'  //
	cOval						= 0x636f766c					//  'covl'  //
};

enum  {
	cParagraph					= 0x63706172,					//  'cpar'  //
	cPICT						= 0x50494354,					//  'PICT'  //
	cPixel						= 0x6370786c,					//  'cpxl'  //
	cPixelMap					= 0x63706978,					//  'cpix'  //
	cPolygon					= 0x6370676e,					//  'cpgn'  //
	cProperty					= 0x70726f70,					//  'prop'  //
	cQDPoint					= 0x51447074,					//  'QDpt'  //
	cQDRectangle				= 0x71647274,					//  'qdrt'  //
	cRectangle					= 0x63726563,					//  'crec'  //
	cRGBColor					= 0x63524742,					//  'cRGB'  //
	cRotation					= 0x74726f74,					//  'trot'  //
	cRoundedRectangle			= 0x63727263,					//  'crrc'  //
	cRow						= 0x63726f77,					//  'crow'  //
	cSelection					= 0x6373656c,					//  'csel'  //
	cShortInteger				= 0x73686f72,					//  'shor'  //
	cTable						= 0x6374626c,					//  'ctbl'  //
	cText						= 0x63747874,					//  'ctxt'  //
	cTextFlow					= 0x63666c6f,					//  'cflo'  //
	cTextStyles					= 0x74737479,					//  'tsty'  //
	cType						= 0x74797065					//  'type'  //
};

enum  {
	cVersion					= 0x76657273,					//  'vers'  //
	cWindow						= 0x6377696e,					//  'cwin'  //
	cWord						= 0x63776f72,					//  'cwor'  //
	enumArrows					= 0x6172726f,					//  'arro'  //
	enumJustification			= 0x6a757374,					//  'just'  //
	enumKeyForm					= 0x6b66726d,					//  'kfrm'  //
	enumPosition				= 0x706f7369,					//  'posi'  //
	enumProtection				= 0x7072746e,					//  'prtn'  //
	enumQuality					= 0x7175616c,					//  'qual'  //
	enumSaveOptions				= 0x7361766f,					//  'savo'  //
	enumStyle					= 0x7374796c,					//  'styl'  //
	enumTransferMode			= 0x7472616e,					//  'tran'  //
	formUniqueID				= 0x49442020,					//  'ID  '  //
	kAEAbout					= 0x61626f75,					//  'abou'  //
	kAEAfter					= 0x61667465,					//  'afte'  //
	kAEAliasSelection			= 0x73616c69,					//  'sali'  //
	kAEAllCaps					= 0x616c6370,					//  'alcp'  //
	kAEArrowAtEnd				= 0x6172656e,					//  'aren'  //
	kAEArrowAtStart				= 0x61727374,					//  'arst'  //
	kAEArrowBothEnds			= 0x6172626f					//  'arbo'  //
};

enum  {
	kAEAsk						= 0x61736b20,					//  'ask '  //
	kAEBefore					= 0x6265666f,					//  'befo'  //
	kAEBeginning				= 0x62676e67,					//  'bgng'  //
	kAEBeginsWith				= 0x62677774,					//  'bgwt'  //
	kAEBeginTransaction			= 0x62656769,					//  'begi'  //
	kAEBold						= 0x626f6c64,					//  'bold'  //
	kAECaseSensEquals			= 0x63736571,					//  'cseq'  //
	kAECentered					= 0x63656e74,					//  'cent'  //
	kAEChangeView				= 0x76696577,					//  'view'  //
	kAEClone					= 0x636c6f6e,					//  'clon'  //
	kAEClose					= 0x636c6f73,					//  'clos'  //
	kAECondensed				= 0x636f6e64,					//  'cond'  //
	kAEContains					= 0x636f6e74,					//  'cont'  //
	kAECopy						= 0x636f7079,					//  'copy'  //
	kAECoreSuite				= 0x636f7265,					//  'core'  //
	kAECountElements			= 0x636e7465,					//  'cnte'  //
	kAECreateElement			= 0x6372656c,					//  'crel'  //
	kAECreatePublisher			= 0x63707562,					//  'cpub'  //
	kAECut						= 0x63757420,					//  'cut '  //
	kAEDelete					= 0x64656c6f					//  'delo'  //
};

enum  {
	kAEDoObjectsExist			= 0x646f6578,					//  'doex'  //
	kAEDoScript					= 0x646f7363,					//  'dosc'  //
	kAEDrag						= 0x64726167,					//  'drag'  //
	kAEDuplicateSelection		= 0x73647570,					//  'sdup'  //
	kAEEditGraphic				= 0x65646974,					//  'edit'  //
	kAEEmptyTrash				= 0x656d7074,					//  'empt'  //
	kAEEnd						= 0x656e6420,					//  'end '  //
	kAEEndsWith					= 0x656e6473,					//  'ends'  //
	kAEEndTransaction			= 0x656e6474,					//  'endt'  //
	kAEEquals					= 0x3d202020,					//  '=   '  //
	kAEExpanded					= 0x70657870,					//  'pexp'  //
	kAEFast						= 0x66617374,					//  'fast'  //
	kAEFinderEvents				= 0x464e4452,					//  'FNDR'  //
	kAEFormulaProtect			= 0x6670726f,					//  'fpro'  //
	kAEFullyJustified			= 0x66756c6c,					//  'full'  //
	kAEGetClassInfo				= 0x716f626a,					//  'qobj'  //
	kAEGetData					= 0x67657464,					//  'getd'  //
	kAEGetDataSize				= 0x6473697a,					//  'dsiz'  //
	kAEGetEventInfo				= 0x67746569,					//  'gtei'  //
	kAEGetInfoSelection			= 0x73696e66					//  'sinf'  //
};

enum  {
	kAEGetPrivilegeSelection	= 0x73707276,					//  'sprv'  //
	kAEGetSuiteInfo				= 0x67747369,					//  'gtsi'  //
	kAEGreaterThan				= 0x3e202020,					//  '>   '  //
	kAEGreaterThanEquals		= 0x3e3d2020,					//  '>=  '  //
	kAEGrow						= 0x67726f77,					//  'grow'  //
	kAEHidden					= 0x6869646e,					//  'hidn'  //
	kAEHiQuality				= 0x68697175,					//  'hiqu'  //
	kAEImageGraphic				= 0x696d6772,					//  'imgr'  //
	kAEIsUniform				= 0x6973756e,					//  'isun'  //
	kAEItalic					= 0x6974616c,					//  'ital'  //
	kAELeftJustified			= 0x6c656674,					//  'left'  //
	kAELessThan					= 0x3c202020,					//  '<   '  //
	kAELessThanEquals			= 0x3c3d2020,					//  '<=  '  //
	kAELowercase				= 0x6c6f7763,					//  'lowc'  //
	kAEMakeObjectsVisible		= 0x6d766973,					//  'mvis'  //
	kAEMiscStandards			= 0x6d697363,					//  'misc'  //
	kAEModifiable				= 0x6d6f6466,					//  'modf'  //
	kAEMove						= 0x6d6f7665,					//  'move'  //
	kAENo						= 0x6e6f2020,					//  'no  '  //
	kAENoArrow					= 0x61726e6f					//  'arno'  //
};

enum  {
	kAENonmodifiable			= 0x6e6d6f64,					//  'nmod'  //
	kAEOpen						= 0x6f646f63,					//  'odoc'  //
	kAEOpenSelection			= 0x736f7065,					//  'sope'  //
	kAEOutline					= 0x6f75746c,					//  'outl'  //
	kAEPageSetup				= 0x70677375,					//  'pgsu'  //
	kAEPaste					= 0x70617374,					//  'past'  //
	kAEPlain					= 0x706c616e,					//  'plan'  //
	kAEPrint					= 0x70646f63,					//  'pdoc'  //
	kAEPrintSelection			= 0x73707269,					//  'spri'  //
	kAEPrintWindow				= 0x7077696e,					//  'pwin'  //
	kAEPutAwaySelection			= 0x73707574,					//  'sput'  //
	kAEQDAddOver				= 0x6164646f,					//  'addo'  //
	kAEQDAddPin					= 0x61646470,					//  'addp'  //
	kAEQDAdMax					= 0x61646d78,					//  'admx'  //
	kAEQDAdMin					= 0x61646d6e,					//  'admn'  //
	kAEQDBic					= 0x62696320,					//  'bic '  //
	kAEQDBlend					= 0x626c6e64,					//  'blnd'  //
	kAEQDCopy					= 0x63707920,					//  'cpy '  //
	kAEQDNotBic					= 0x6e626963,					//  'nbic'  //
	kAEQDNotCopy				= 0x6e637079					//  'ncpy'  //
};

enum  {
	kAEQDNotOr					= 0x6e746f72,					//  'ntor'  //
	kAEQDNotXor					= 0x6e786f72,					//  'nxor'  //
	kAEQDOr						= 0x6f722020,					//  'or  '  //
	kAEQDSubOver				= 0x7375626f,					//  'subo'  //
	kAEQDSubPin					= 0x73756270,					//  'subp'  //
	kAEQDSupplementalSuite		= 0x71647370,					//  'qdsp'  //
	kAEQDXor					= 0x786f7220,					//  'xor '  //
	kAEQuickdrawSuite			= 0x71647277,					//  'qdrw'  //
	kAEQuitAll					= 0x71756961,					//  'quia'  //
	kAERedo						= 0x7265646f,					//  'redo'  //
	kAERegular					= 0x7265676c,					//  'regl'  //
	kAEReplace					= 0x72706c63,					//  'rplc'  //
	kAERequiredSuite			= 0x72657164,					//  'reqd'  //
	kAERestart					= 0x72657374,					//  'rest'  //
	kAERevealSelection			= 0x73726576,					//  'srev'  //
	kAERevert					= 0x72767274,					//  'rvrt'  //
	kAERightJustified			= 0x72676874,					//  'rght'  //
	kAESave						= 0x73617665,					//  'save'  //
	kAESelect					= 0x736c6374,					//  'slct'  //
	kAESetData					= 0x73657464					//  'setd'  //
};

enum  {
	kAESetPosition				= 0x706f736e,					//  'posn'  //
	kAEShadow					= 0x73686164,					//  'shad'  //
	kAEShowClipboard			= 0x7368636c,					//  'shcl'  //
	kAEShutDown					= 0x73687574,					//  'shut'  //
	kAESleep					= 0x736c6570,					//  'slep'  //
	kAESmallCaps				= 0x736d6370,					//  'smcp'  //
	kAESpecialClassProperties	= 0x63402321,					//  'c@#!'  //
	kAEStrikethrough			= 0x7374726b,					//  'strk'  //
	kAESubscript				= 0x73627363,					//  'sbsc'  //
	kAESuperscript				= 0x73707363,					//  'spsc'  //
	kAETableSuite				= 0x74626c73,					//  'tbls'  //
	kAETextSuite				= 0x54455854,					//  'TEXT'  //
	kAETransactionTerminated	= 0x7474726d,					//  'ttrm'  //
	kAEUnderline				= 0x756e646c,					//  'undl'  //
	kAEUndo						= 0x756e646f,					//  'undo'  //
	kAEWholeWordEquals			= 0x77776571,					//  'wweq'  //
	kAEYes						= 0x79657320,					//  'yes '  //
	kAEZoom						= 0x7a6f6f6d,					//  'zoom'  //
	keyAEAngle					= 0x6b616e67,					//  'kang'  //
	keyAEArcAngle				= 0x70617263					//  'parc'  //
};

enum  {
	keyAEBaseAddr				= 0x62616464,					//  'badd'  //
	keyAEBestType				= 0x70627374,					//  'pbst'  //
	keyAEBgndColor				= 0x6b62636c,					//  'kbcl'  //
	keyAEBgndPattern			= 0x6b627074,					//  'kbpt'  //
	keyAEBounds					= 0x70626e64,					//  'pbnd'  //
	keyAECellList				= 0x6b636c74,					//  'kclt'  //
	keyAEClassID				= 0x636c4944,					//  'clID'  //
	keyAEColor					= 0x636f6c72,					//  'colr'  //
	keyAEColorTable				= 0x636c7462,					//  'cltb'  //
	keyAECurveHeight			= 0x6b636864,					//  'kchd'  //
	keyAECurveWidth				= 0x6b637764,					//  'kcwd'  //
	keyAEDashStyle				= 0x70647374,					//  'pdst'  //
	keyAEData					= 0x64617461,					//  'data'  //
	keyAEDefaultType			= 0x64656674,					//  'deft'  //
	keyAEDefinitionRect			= 0x70647274,					//  'pdrt'  //
	keyAEDescType				= 0x64737470,					//  'dstp'  //
	keyAEDestination			= 0x64657374,					//  'dest'  //
	keyAEDoAntiAlias			= 0x616e7461,					//  'anta'  //
	keyAEDoDithered				= 0x67646974,					//  'gdit'  //
	keyAEDoRotate				= 0x6b647274					//  'kdrt'  //
};

enum  {
	keyAEDoScale				= 0x6b736361,					//  'ksca'  //
	keyAEDoTranslate			= 0x6b747261,					//  'ktra'  //
	keyAEEditionFileLoc			= 0x656c6f63,					//  'eloc'  //
	keyAEElements				= 0x656c6d73,					//  'elms'  //
	keyAEEndPoint				= 0x70656e64,					//  'pend'  //
	keyAEEventClass				= 0x6576636c,					//  'evcl'  //
	keyAEEventID				= 0x65767469,					//  'evti'  //
	keyAEFile					= 0x6b66696c,					//  'kfil'  //
	keyAEFileType				= 0x666c7470,					//  'fltp'  //
	keyAEFillColor				= 0x666c636c,					//  'flcl'  //
	keyAEFillPattern			= 0x666c7074,					//  'flpt'  //
	keyAEFlipHorizontal			= 0x6b66686f,					//  'kfho'  //
	keyAEFlipVertical			= 0x6b667674,					//  'kfvt'  //
	keyAEFont					= 0x666f6e74,					//  'font'  //
	keyAEFormula				= 0x70666f72,					//  'pfor'  //
	keyAEGraphicObjects			= 0x676f6273,					//  'gobs'  //
	keyAEID						= 0x49442020,					//  'ID  '  //
	keyAEImageQuality			= 0x67717561,					//  'gqua'  //
	keyAEInsertHere				= 0x696e7368,					//  'insh'  //
	keyAEKeyForms				= 0x6b657966					//  'keyf'  //
};

enum  {
	keyAEKeyword				= 0x6b797764,					//  'kywd'  //
	keyAELevel					= 0x6c65766c,					//  'levl'  //
	keyAELineArrow				= 0x6172726f,					//  'arro'  //
	keyAEName					= 0x706e616d,					//  'pnam'  //
	keyAENewElementLoc			= 0x706e656c,					//  'pnel'  //
	keyAEObject					= 0x6b6f626a,					//  'kobj'  //
	keyAEObjectClass			= 0x6b6f636c,					//  'kocl'  //
	keyAEOffStyles				= 0x6f667374,					//  'ofst'  //
	keyAEOnStyles				= 0x6f6e7374,					//  'onst'  //
	keyAEParameters				= 0x70726d73,					//  'prms'  //
	keyAEParamFlags				= 0x706d6667,					//  'pmfg'  //
	keyAEPenColor				= 0x7070636c,					//  'ppcl'  //
	keyAEPenPattern				= 0x70707061,					//  'pppa'  //
	keyAEPenWidth				= 0x70707764,					//  'ppwd'  //
	keyAEPixelDepth				= 0x70647074,					//  'pdpt'  //
	keyAEPixMapMinus			= 0x6b706d6d,					//  'kpmm'  //
	keyAEPMTable				= 0x6b706d74,					//  'kpmt'  //
	keyAEPointList				= 0x70746c74,					//  'ptlt'  //
	keyAEPointSize				= 0x7074737a,					//  'ptsz'  //
	keyAEPosition				= 0x6b706f73					//  'kpos'  //
};

enum  {
	keyAEPropData				= 0x70726474,					//  'prdt'  //
	keyAEProperties				= 0x7170726f,					//  'qpro'  //
	keyAEProperty				= 0x6b707270,					//  'kprp'  //
	keyAEPropFlags				= 0x70726667,					//  'prfg'  //
	keyAEPropID					= 0x70726f70,					//  'prop'  //
	keyAEProtection				= 0x7070726f,					//  'ppro'  //
	keyAERenderAs				= 0x6b72656e,					//  'kren'  //
	keyAERequestedType			= 0x72747970,					//  'rtyp'  //
	keyAEResult					= 0x2d2d2d2d,					//  '----'  //
	keyAEResultInfo				= 0x7273696e,					//  'rsin'  //
	keyAERotation				= 0x70726f74,					//  'prot'  //
	keyAERotPoint				= 0x6b727470,					//  'krtp'  //
	keyAERowList				= 0x6b726c73,					//  'krls'  //
	keyAESaveOptions			= 0x7361766f,					//  'savo'  //
	keyAEScale					= 0x7073636c,					//  'pscl'  //
	keyAEScriptTag				= 0x70736374,					//  'psct'  //
	keyAEShowWhere				= 0x73686f77,					//  'show'  //
	keyAEStartAngle				= 0x70616e67,					//  'pang'  //
	keyAEStartPoint				= 0x70737470,					//  'pstp'  //
	keyAEStyles					= 0x6b737479					//  'ksty'  //
};

enum  {
	keyAESuiteID				= 0x73756974,					//  'suit'  //
	keyAEText					= 0x6b747874,					//  'ktxt'  //
	keyAETextColor				= 0x70747863,					//  'ptxc'  //
	keyAETextFont				= 0x70747866,					//  'ptxf'  //
	keyAETextPointSize			= 0x70747073,					//  'ptps'  //
	keyAETextStyles				= 0x74787374,					//  'txst'  //
	keyAETheText				= 0x74687478,					//  'thtx'  //
	keyAETransferMode			= 0x7070746d,					//  'pptm'  //
	keyAETranslation			= 0x70747273,					//  'ptrs'  //
	keyAETryAsStructGraf		= 0x746f6f67,					//  'toog'  //
	keyAEUniformStyles			= 0x7573746c,					//  'ustl'  //
	keyAEUpdateOn				= 0x70757064,					//  'pupd'  //
	keyAEUserTerm				= 0x7574726d,					//  'utrm'  //
	keyAEWindow					= 0x776e6477,					//  'wndw'  //
	keyAEWritingCode			= 0x77726364,					//  'wrcd'  //
	keyAETSMScriptTag			= 'sclg',
	keyAETSMTextFont			= 'ktxf',
	keyAETSMTextPointSize		= 'ktps',
	keyMiscellaneous			= 0x666d7363					//  'fmsc'  //
};

enum  {
	keySelection				= 0x6673656c,					//  'fsel'  //
	keyWindow					= 0x6b776e64					//  'kwnd'  //
};

enum  {
	pArcAngle					= 0x70617263,					//  'parc'  //
	pBackgroundColor			= 0x7062636c,					//  'pbcl'  //
	pBackgroundPattern			= 0x70627074,					//  'pbpt'  //
	pBestType					= 0x70627374,					//  'pbst'  //
	pBounds						= 0x70626e64,					//  'pbnd'  //
	pClass						= 0x70636c73,					//  'pcls'  //
	pClipboard					= 0x70636c69,					//  'pcli'  //
	pColor						= 0x636f6c72,					//  'colr'  //
	pColorTable					= 0x636c7462,					//  'cltb'  //
	pContents					= 0x70636e74,					//  'pcnt'  //
	pCornerCurveHeight			= 0x70636864,					//  'pchd'  //
	pCornerCurveWidth			= 0x70637764,					//  'pcwd'  //
	pDashStyle					= 0x70647374,					//  'pdst'  //
	pDefaultType				= 0x64656674,					//  'deft'  //
	pDefinitionRect				= 0x70647274,					//  'pdrt'  //
	pEnabled					= 0x656e626c,					//  'enbl'  //
	pEndPoint					= 0x70656e64,					//  'pend'  //
	pFillColor					= 0x666c636c,					//  'flcl'  //
	pFillPattern				= 0x666c7074,					//  'flpt'  //
	pFont						= 0x666f6e74					//  'font'  //
};

enum  {
	pFormula					= 0x70666f72,					//  'pfor'  //
	pGraphicObjects				= 0x676f6273,					//  'gobs'  //
	pHasCloseBox				= 0x68636c62,					//  'hclb'  //
	pHasTitleBar				= 0x70746974,					//  'ptit'  //
	pID							= 0x49442020,					//  'ID  '  //
	pIndex						= 0x70696478,					//  'pidx'  //
	pInsertionLoc				= 0x70696e73,					//  'pins'  //
	pIsFloating					= 0x6973666c,					//  'isfl'  //
	pIsFrontProcess				= 0x70697366,					//  'pisf'  //
	pIsModal					= 0x706d6f64,					//  'pmod'  //
	pIsModified					= 0x696d6f64,					//  'imod'  //
	pIsResizable				= 0x7072737a,					//  'prsz'  //
	pIsStationeryPad			= 0x70737064,					//  'pspd'  //
	pIsZoomable					= 0x69737a6d,					//  'iszm'  //
	pIsZoomed					= 0x707a756d,					//  'pzum'  //
	pItemNumber					= 0x69746d6e,					//  'itmn'  //
	pJustification				= 0x706a7374,					//  'pjst'  //
	pLineArrow					= 0x6172726f,					//  'arro'  //
	pMenuID						= 0x6d6e6964,					//  'mnid'  //
	pName						= 0x706e616d					//  'pnam'  //
};

enum  {
	pNewElementLoc				= 0x706e656c,					//  'pnel'  //
	pPenColor					= 0x7070636c,					//  'ppcl'  //
	pPenPattern					= 0x70707061,					//  'pppa'  //
	pPenWidth					= 0x70707764,					//  'ppwd'  //
	pPixelDepth					= 0x70647074,					//  'pdpt'  //
	pPointList					= 0x70746c74,					//  'ptlt'  //
	pPointSize					= 0x7074737a,					//  'ptsz'  //
	pProtection					= 0x7070726f,					//  'ppro'  //
	pRotation					= 0x70726f74,					//  'prot'  //
	pScale						= 0x7073636c,					//  'pscl'  //
	pScript						= 0x73637074,					//  'scpt'  //
	pScriptTag					= 0x70736374,					//  'psct'  //
	pSelected					= 0x73656c63,					//  'selc'  //
	pSelection					= 0x73656c65,					//  'sele'  //
	pStartAngle					= 0x70616e67,					//  'pang'  //
	pStartPoint					= 0x70737470,					//  'pstp'  //
	pTextColor					= 0x70747863,					//  'ptxc'  //
	pTextFont					= 0x70747866,					//  'ptxf'  //
	pTextItemDelimiters			= 0x7478646c,					//  'txdl'  //
	pTextPointSize				= 0x70747073					//  'ptps'  //
};

enum  {
	pTextStyles					= 0x74787374,					//  'txst'  //
	pTransferMode				= 0x7070746d,					//  'pptm'  //
	pTranslation				= 0x70747273,					//  'ptrs'  //
	pUniformStyles				= 0x7573746c,					//  'ustl'  //
	pUpdateOn					= 0x70757064,					//  'pupd'  //
	pUserSelection				= 0x7075736c,					//  'pusl'  //
	pVersion					= 0x76657273,					//  'vers'  //
	pVisible					= 0x70766973					//  'pvis'  //
};

enum  {
	typeAEText					= 0x74545854,					//  'tTXT'  //
	typeArc						= 0x63617263,					//  'carc'  //
	typeBest					= 0x62657374,					//  'best'  //
	typeCell					= 0x6363656c,					//  'ccel'  //
	typeClassInfo				= 0x67636c69,					//  'gcli'  //
	typeColorTable				= 0x636c7274,					//  'clrt'  //
	typeColumn					= 0x63636f6c,					//  'ccol'  //
	typeDashStyle				= 0x74646173,					//  'tdas'  //
	typeData					= 0x74647461,					//  'tdta'  //
	typeDrawingArea				= 0x63647277,					//  'cdrw'  //
	typeElemInfo				= 0x656c696e,					//  'elin'  //
	typeEnumeration				= 0x656e756d,					//  'enum'  //
	typeEPS						= 0x45505320,					//  'EPS '  //
	typeEventInfo				= 0x6576696e					//  'evin'  //
};

enum  {
	typeFinderWindow			= 0x6677696e,					//  'fwin'  //
	typeFixed					= 0x66697864,					//  'fixd'  //
	typeFixedPoint				= 0x66706e74,					//  'fpnt'  //
	typeFixedRectangle			= 0x66726374,					//  'frct'  //
	typeGraphicLine				= 0x676c696e,					//  'glin'  //
	typeGraphicText				= 0x63677478,					//  'cgtx'  //
	typeGroupedGraphic			= 0x63706963,					//  'cpic'  //
	typeInsertionLoc			= 0x696e736c,					//  'insl'  //
	typeIntlText				= 0x69747874,					//  'itxt'  //
	typeIntlWritingCode			= 0x696e746c,					//  'intl'  //
	typeLongDateTime			= 0x6c647420,					//  'ldt '  //
	typeLongFixed				= 0x6c667864,					//  'lfxd'  //
	typeLongFixedPoint			= 0x6c667074,					//  'lfpt'  //
	typeLongFixedRectangle		= 0x6c667263,					//  'lfrc'  //
	typeLongPoint				= 0x6c706e74,					//  'lpnt'  //
	typeLongRectangle			= 0x6c726374,					//  'lrct'  //
	typeMachineLoc				= 0x6d4c6f63,					//  'mLoc'  //
	typeOval					= 0x636f766c,					//  'covl'  //
	typeParamInfo				= 0x706d696e,					//  'pmin'  //
	typePict					= 0x50494354					//  'PICT'  //
};

enum  {
	typePixelMap				= 0x63706978,					//  'cpix'  //
	typePixMapMinus				= 0x74706d6d,					//  'tpmm'  //
	typePolygon					= 0x6370676e,					//  'cpgn'  //
	typePropInfo				= 0x70696e66,					//  'pinf'  //
	typeQDPoint					= 0x51447074,					//  'QDpt'  //
	typeQDRectangle				= 0x71647274,					//  'qdrt'  //
	typeRectangle				= 0x63726563,					//  'crec'  //
	typeRGB16					= 0x74723136,					//  'tr16'  //
	typeRGB96					= 0x74723936,					//  'tr96'  //
	typeRGBColor				= 0x63524742,					//  'cRGB'  //
	typeRotation				= 0x74726f74,					//  'trot'  //
	typeRoundedRectangle		= 0x63727263,					//  'crrc'  //
	typeRow						= 0x63726f77,					//  'crow'  //
	typeScrapStyles				= 0x7374796c,					//  'styl'  //
	typeScript					= 0x73637074,					//  'scpt'  //
	typeStyledText				= 0x53545854,					//  'STXT'  //
	typeSuiteInfo				= 0x7375696e,					//  'suin'  //
	typeTable					= 0x6374626c,					//  'ctbl'  //
	typeTextStyles				= 0x74737479					//  'tsty'  //
};

enum  {
	typeTIFF					= 0x54494646,					//  'TIFF'  //
	typeVersion					= 0x76657273					//  'vers'  //
};

enum  {
	kBySmallIcon				= 0,
	kByIconView					= 1,
	kByNameView					= 2,
	kByDateView					= 3,
	kBySizeView					= 4,
	kByKindView					= 5,
	kByCommentView				= 6,
	kByLabelView				= 7,
	kByVersionView				= 8
};

enum  {
	errAEBadKeyForm				= -10002,
	errAECantHandleClass		= -10010,
	errAECantSupplyType			= -10009,
	errAECantUndo				= -10015,
	errAEEventFailed			= -10000,
	errAEIndexTooLarge			= -10007,
	errAEInTransaction			= -10011,
	errAELocalOnly				= -10016,
	errAENoSuchTransaction		= -10012,
	errAENotAnElement			= -10008,
	errAENotASingleObject		= -10014,
	errAENotModifiable			= -10003,
	errAENoUserSelection		= -10013,
	errAEPrivilegeError			= -10004,
	errAEReadDenied				= -10005,
	errAETypeError				= -10001,
	errAEWriteDenied			= -10006
};

enum  {
	kAEInfo						= 11,
	kAEMain						= 0,
	kAESharing					= 13
};

enum  {
	zoomIn						= 7,
	zoomOut						= 8
};

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct WritingCode {
	ScriptCode					theScriptCode;
	LangCode					theLangCode;
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct WritingCode WritingCode;

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct IntlText {
	ScriptCode					theScriptCode;
	LangCode					theLangCode;
	char						theText[1];
/* variable length data */
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct IntlText IntlText;

#endif

