/*
	File:		AEUserTermTypes.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __AEUserTermTypes__
#define __AEUserTermTypes__

enum  {
	kAEUserTerminology			= 0x61657574,					//  'aeut'  // 
	kAETerminologyExtension		= 0x61657465,					//  'aete'  // 
	kAEScriptingSizeResource	= 0x7363737a					//  'scsz'  // 
};

enum  {
	kAEUTHasReturningParam		= 31,							// if event has a keyASReturning param
	kAEUTOptional				= 15,							// if something is optional
	kAEUTlistOfItems			= 14,							// if property or reply is a list.
	kAEUTEnumerated				= 13,							// if property or reply is of an enumerated type.
	kAEUTReadWrite				= 12,							// if property is writable.
	kAEUTChangesState			= 12,							// if an event changes state.
	kAEUTTightBindingFunction	= 12,							// if this is a tight-binding precedence function.
	kAEUTApostrophe				= 3,							// if a term contains an apostrophe.
	kAEUTFeminine				= 2,							// if a term is feminine gender.
	kAEUTMasculine				= 1,							// if a term is masculine gender.
	kAEUTPlural					= 0								// if a term is plural.
};

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct TScriptingSizeResource {
	short						scriptingSizeFlags;
	unsigned long				minStackSize;
	unsigned long				preferredStackSize;
	unsigned long				maxStackSize;
	unsigned long				minHeapSize;
	unsigned long				preferredHeapSize;
	unsigned long				maxHeapSize;
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

enum  {
	kLaunchToGetTerminology		= (1 << 15),
// if 0, read aete directly from res file; if 1, then launch and use gdut event 
	kDontFindAppBySignature		= (1 << 14),
// if 0, then find app with signature if lost; if 1, then don't
	kAlwaysSendSubject			= (1 << 13)
};


// if 0, then send subject when appropriate; if 1, then every event has Subject Attribute


// old names for above bits.

enum  {
	kReadExtensionTermsMask		= (1 << 15)
};

#endif

