/*
	File:		Disks.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __DISKS__
#define __DISKS__

#ifndef __TYPES__
#include <Types.h>
/*	#include <ConditionalMacros.h>								*/
/*	#include <MixedMode.h>										*/
/*		#include <Traps.h>										*/
#endif

#ifndef __OSUTILS__
#include <OSUtils.h>
#endif

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct DrvSts {
	short						track;							/*current track*/
	char						writeProt;						/*bit 7 = 1 if volume is locked*/
	char						diskInPlace;					/*disk in drive*/
	char						installed;						/*drive installed*/
	char						sides;							/*-1 for 2-sided, 0 for 1-sided*/
	QElemPtr					qLink;							/*next queue entry*/
	short						qType;							/*1 for HD20*/
	short						dQDrive;						/*drive number*/
	short						dQRefNum;						/*driver reference number*/
	short						dQFSID;							/*file system ID*/
	char						twoSideFmt;						/*after 1st rd/wrt: 0=1 side, -1=2 side*/
	char						needsFlush;						/*-1 for MacPlus drive*/
	short						diskErrs;						/*soft error count*/
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct DrvSts DrvSts;

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct DrvSts2 {
	short						track;
	char						writeProt;
	char						diskInPlace;
	char						installed;
	char						sides;
	QElemPtr					qLink;
	short						qType;
	short						dQDrive;
	short						dQRefNum;
	short						dQFSID;
	short						driveSize;
	short						driveS1;
	short						driveType;
	short						driveManf;
	short						driveChar;
	char						driveMisc;
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct DrvSts2 DrvSts2;

#ifdef __cplusplus
extern "C" {
#endif

extern pascal OSErr DiskEject(short drvNum);
extern pascal OSErr SetTagBuffer(void *buffPtr);
extern pascal OSErr DriveStatus(short drvNum, DrvSts *status);
#ifdef __cplusplus
}
#endif

#endif

