/*
	File:		OSAComp.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __OSAComp__
#define __OSAComp__

#ifndef __OSA__
#include <OSA.h>
/*	#include <AppleEvents.h>									*/
/*		#include <Types.h>										*/
/*			#include <ConditionalMacros.h>						*/
/*			#include <MixedMode.h>								*/
/*				#include <Traps.h>								*/
/*		#include <Memory.h>										*/
/*		#include <OSUtils.h>									*/
/*		#include <Events.h>										*/
/*			#include <Quickdraw.h>								*/
/*				#include <QuickdrawText.h>						*/
/*					#include <IntlResources.h>					*/
/*		#include <EPPC.h>										*/
/*			#include <PPCToolBox.h>								*/
/*				#include <AppleTalk.h>							*/
/*			#include <Processes.h>								*/
/*				#include <Files.h>								*/
/*					#include <SegLoad.h>						*/
/*		#include <Notification.h>								*/
/*	#include <AEObjects.h>										*/
/*	#include <Components.h>										*/
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern pascal OSErr OSAGetStorageType(Handle scriptData, DescType *type);
extern pascal OSErr OSAAddStorageType(Handle scriptData, DescType type);
extern pascal OSErr OSARemoveStorageType(Handle scriptData);

////////////////////////////////////////////////////////////////////////////////

#ifdef __cplusplus
}
#endif

#endif

