/*
	File:		Scrap.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __SCRAP__
#define __SCRAP__

#ifndef __TYPES__
#include <Types.h>
/*	#include <ConditionalMacros.h>								*/
/*	#include <MixedMode.h>										*/
/*		#include <Traps.h>										*/
#endif

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct ScrapStuff {
	long						scrapSize;
	Handle						scrapHandle;
	short						scrapCount;
	short						scrapState;
	StringPtr					scrapName;
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct ScrapStuff ScrapStuff;

typedef ScrapStuff *PScrapStuff;

#ifdef __cplusplus
extern "C" {
#endif

extern pascal PScrapStuff InfoScrap(void)
 ONEWORDINLINE(0xA9F9);
extern pascal long UnloadScrap(void)
 ONEWORDINLINE(0xA9FA);
extern pascal long LoadScrap(void)
 ONEWORDINLINE(0xA9FB);
extern pascal long GetScrap(Handle hDest, ResType theType, long *offset)
 ONEWORDINLINE(0xA9FD);
extern pascal long ZeroScrap(void)
 ONEWORDINLINE(0xA9FC);
extern pascal long PutScrap(long length, ResType theType, Ptr source)
 ONEWORDINLINE(0xA9FE);
#ifdef __cplusplus
}
#endif

#endif

