/*
	File:		SegLoad.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __SEGLOAD__
#define __SEGLOAD__

#ifndef __TYPES__
#include <Types.h>
/*	#include <ConditionalMacros.h>								*/
/*	#include <MixedMode.h>										*/
/*		#include <Traps.h>										*/
#endif

enum  {
	appOpen						= 0,							/*Open the Document (s)*/
	appPrint					= 1								/*Print the Document (s)*/
};

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct AppFile {
	short						vRefNum;
	OSType						fType;
	short						versNum;						/*versNum in high byte*/
	Str255						fName;
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

typedef struct AppFile AppFile;

#ifdef __cplusplus
extern "C" {
#endif


/*
	Because PowerPC applications don’t have segments, this
	UnloadSeg is unsupported for PowerPC.
*/

#if !defined(powerc) && !defined(__powerc)
extern pascal void UnloadSeg(void *routineAddr)
 ONEWORDINLINE(0xA9F1);
#else
#define UnloadSeg(x)

#endif


/*
	CountAppFiles, GetAppFiles, ClrAppFiles, GetAppParms, and 
	getappparms are obsolete. They are still supported for 68K 
	apps (if OBSOLETE is defined), but they are not supported 
	for PowerPC apps. Use AppleEvents to determine which files
	are to be opened or printed from the Finder.
*/

#if defined(OBSOLETE) && !defined(powerc) && !defined(__powerc)
extern pascal void CountAppFiles(short *message, short *count);
extern pascal void GetAppFiles(short index, AppFile *theFile);
extern pascal void ClrAppFiles(short index);
extern pascal void GetAppParms(Str255 apName, short *apRefNum, Handle *apParam)
 ONEWORDINLINE(0xA9F5);
extern void getappparms(char *apName, short *apRefNum, Handle *apParam);
#endif

extern pascal void ExitToShell(void)
 ONEWORDINLINE(0xA9F4);
#ifdef __cplusplus
}
#endif

#endif

