/*
	Errors.h -- Macintosh ROM Error Values

	C Interface to the Macintosh Libraries
	Copyright Apple Computer,Inc. 1985,1986
	All rights reserved.
*/

#ifndef __ERRORS__
#define __ERRORS__

#define sktClosedErr (-3109)
#define recNotFnd (-3108)
#define atpBadRsp (-3107)
#define atpLenErr (-3106)
#define readQErr (-3105)
#define extractErr (-3104)
#define ckSumErr (-3103)
#define noMPPErr (-3102)
#define buf2SmallErr (-3101)
#define reqAborted (-1105)
#define noDataArea (-1104)
#define noSendResp (-1103)
#define cbNotFound (-1102)
#define noRelErr (-1101)
#define badBuffNum (-1100)
#define badATPSkt (-1099)
#define tooManySkts (-1098)
#define tooManyReqs (-1097)
#define reqFailed (-1096)
#define nbpNISErr (-1029)
#define nbpNotFound (-1028)
#define nbpDuplicate (-1027)
#define nbpConfDiff (-1026)
#define nbpNoConfirm (-1025)
#define nbpBuffOvr (-1024)
#define mapReadErr (-199)
#define resAttrErr (-198)
#define rmvRefFailed (-197)
#define rmvResFailed (-196)
#define addRefFailed (-195)
#define addResFailed (-194)
#define resFNotFound (-193)
#define resNotFound (-192)
#define fsDSIntErr (-127)
#define wrgVolTypErr (-123)
#define badMovErr (-122)
#define tmwdoErr (-121)
#define dirNFErr (-120)
#define memLockedErr (-117)
#define memSCErr (-116)
#define memBCErr (-115)
#define memPCErr (-114)
#define memAZErr (-113)
#define memPurErr (-112)
#define memWZErr (-111)
#define memAdrErr (-110)
#define nilHandleErr (-109)
#define memFullErr (-108)
#define noTypeErr (-102)
#define noScrapErr (-100)
#define memROZErr (-99)
#define portInUse (-97)
#define portNotCf (-98)
#define excessCollsns (-95)
#define lapProtErr (-94)
#define noBridgeErr (-93)
#define ddpLenErr (-92)
#define ddpSktErr (-91)
#define breakRecd (-90)
#define rcvrErr (-89)
#define prInitErr (-88)
#define prWrErr (-87)
#define clkWrErr (-86)
#define clkRdErr (-85)
#define firstDskErr (-84)
#define sectNFErr (-81)
#define seekErr (-80)
#define spdAdjErr (-79)
#define twoSideErr (-78)
#define initIWMErr (-77)
#define tk0BadErr (-76)
#define cantStepErr (-75)
#define wrUnderrun (-74)
#define badDBtSlp (-73)
#define badDCksum (-72)
#define noDtaMkErr (-71)
#define badBtSlpErr (-70)
#define badCksmErr (-69)
#define dataVerErr (-68)
#define noAdrMkErr (-67)
#define noNybErr (-66)
#define fontSubErr (-66)
#define offLinErr (-65)
#define fontNotDeclared (-65)
#define fontDecError (-64)
#define lastDskErr (-64)
#define noDriveErr (-64)
#define wrPermErr (-61)
#define badMDBErr (-60)
#define fsRnErr (-59)
#define extFSErr (-58)
#define noMacDskErr (-57)
#define nsDrvErr (-56)
#define volOnLinErr (-55)
#define permErr (-54)
#define volOffLinErr (-53)
#define gfpErr (-52)
#define rfNumErr (-51)
#define paramErr (-50)
#define opWrErr (-49)
#define dupFNErr (-48)
#define fBsyErr (-47)
#define vLckdErr (-46)
#define fLckdErr (-45)
#define wPrErr (-44)
#define fnfErr (-43)
#define tmfoErr (-42)
#define mFulErr (-41)
#define posErr (-40)
#define eofErr (-39)
#define fnOpnErr (-38)
#define bdNamErr (-37)
#define ioErr (-36)
#define nsvErr (-35)
#define dskFulErr (-34)
#define dirFulErr (-33)
#define notOpenErr (-28)
#define abortErr (-27)
#define iIOAbort (-27)
#define dInstErr (-26)
#define dRemoveErr (-25)
#define closeErr (-24)
#define openErr (-23)
#define unitEmptyErr (-22)
#define badUnitErr (-21)
#define writErr (-20)
#define readErr (-19)
#define statusErr (-18)
#define controlErr (-17)
#define SENoDB (-8)
#define unimpErr (-4)
#define corErr (-3)
#define vTypErr (-2)
#define qErr (-1)
#define noErr 0
#define dsBusErr 1
#define evtNotEnb 1
#define swOverrunErr 1
#define dsAddressErr 2
#define scCommErr 2
#define dsIllInstErr 3
#define dsZeroDivErr 4
#define scBadParmsErr 4
#define dsChkErr 5
#define scPhaseErr 5
#define scCompareErr 6
#define dsOvflowErr 6
#define dsPrivErr 7
#define dsTraceErr 8
#define dsLineAErr 9
#define dsLineFErr 10
#define dsMiscErr 11
#define dsCoreErr 12
#define dsIrqErr 13
#define dsIOCoreErr 14
#define dsLoadErr 15
#define dsFPErr 16
#define parityErr 16
#define dsNoPackErr 17
#define dsMemFullErr 25
#define dsFSErr 27
#define dsStknHeap 28
#define dsReinsert 30
#define dsNotThe1 31
#define hwOverrunErr 32
#define framingErr 64
#define menuPrgErr 84
#define dsSysErr 32767
#endif
