#	MakeFile	-  Make instructions for Pascal examples.
#
#	Copyright Apple Computer, Inc. 1986-1993
#	All rights reserved.
#
#	This makefile builds:
#		The sample Pascal tool: 		ResEqual
#		The sample desk accessory:		Memory
#		The sample Performance Tool: 	TestPerf
#

# 	You can define {SymOptions} as "-sym on" or "-sym off" for use with SADE

POptions = {SymOptions}

#	The following two variables define the creator and type for the
#	Memory Desk Accessory.  For System 6 compatibility, the build
#	instructions should create a "Suitcase" file containing the DA.
#	Suitcase files have a creator of 'DMOV' and a type of 'DFIL'.  For
#	System 7 and newer, DA's can exist all by themselves, without being
#	wrapped in the "womb" of the Suitcase file.  This makes it easier
#	to manipulate the DA file, since the Suitcase doesn't have to be
#	opened first.  DA's can be treated just like any other application.
#	In this case, the creator should be 'movr' and the type should be
#	'dfil' (note the difference in character case).

DACreator	=	'movr'	# change to 'DMOV' for System 6 use
DAType		=	'dfil'	# change to 'DFIL' for System 6 use

# The following variable is used to define the ROM map file used by the
# TestPerf component.  If necessary, you can change this to point to the
# proper location of your machine's ROM map.

RomMapLoc	=	"{MPW}ROM Maps:"
RomMap	  	=	"Mac`gestalt mach -s`ROM.map"

#######################################################################
# Build instructions and dependencies for the ResEqual tool
#

ResEqual		ƒƒ	ResEqual.r
	rez ResEqual.r -o ResEqual -append
ResEqual		ƒƒ	ResEqual.p.o FStubs.a.o
	Link -w -c 'MPS ' -t MPST ResEqual.p.o FStubs.a.o ∂
		-sn STDIO=Main ∂
		-sn INTENV=Main ∂
		-sn %A5Init=Init ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"Runtime.o ∂
		"{Libraries}"ToolLibs.o ∂
		"{PLibraries}"Paslib.o ∂
		-o ResEqual


#######################################################################
# Build instructions and dependencies for the Memory desk accessory
#

Memory			ƒƒ	Memory.p.o DAEntry.a.o 
	Link {SymOptions} -w -da -rt DRVR=12 ∂
		-m DAEntry -sg Memory				# DAEntry is located in DAEntry.a.o ∂
		DAEntry.a.o							# This must preceed DRVRRuntime.o ∂
		"{Libraries}"DRVRRuntime.o			# This must preceed Memory.p.o ∂
		Memory.p.o ∂
		"{Libraries}"Interface.o ∂
		"{PLibraries}"Paslib.o ∂
		-o Memory -c {DACreator} -t {DAType}
		
Memory			ƒƒ	Memory.r
	Rez -rd -c {DACreator} -t {DAType} Memory.r -a -o Memory

Memory.NOASM			ƒ	Memory.DRVW Memory.r
	Rez -rd -c {DACreator} -t {DAType} -d NOASM_BUILD Memory.r -o Memory.NOASM
	Duplicate -y Memory.NOASM Memory

Memory.DRVW 	ƒ	Memory.p.o
	Link -w -rt DRVW=0 ∂
		-sg Memory ∂
		"{Libraries}"DRVRRuntime.o	# This must preceed Memory.p.o ∂
		Memory.p.o ∂
		"{Libraries}"Interface.o ∂
		"{PLibraries}"Paslib.o ∂
		-o Memory.DRVW -c "????" -t "????"


#######################################################################
# Build instructions and dependencies for the TestPerf tool
#

TestPerf	ƒ	TestPerf.p.o
	Link -o TestPerf -t MPST -c 'MPS ' -d ∂
		-l -la > TestPerf.map # produce link map file ∂
		TestPerf.p.o "{Libraries}"PerformLib.o ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"Runtime.o ∂
		"{PLibraries}"PasLib.o
	Set ThisDir `Directory`
	Directory {RomMapLoc}
	Make {RomMap} >"{TempFolder}"Make.Out
	"{TempFolder}"Make.Out && Delete "{TempFolder}"Make.out
	Directory {ThisDir}
	Unset ThisDir
	Catenate {RomMapLoc}{ROMMap} >>TestPerf.map
