#	MakeFile	-  Make instructions for Pascal examples.
#
#	Copyright Apple Computer, Inc. 1986-1988
#	All rights reserved.
#
#	This makefile builds:
#		The sample Pascal tool: 		ResEqual
#		The sample desk accessory:		Memory
#		The sample Performance Tool: 	TestPerf
#


ResEqual		ƒƒ	ResEqual.r
	rez ResEqual.r -o ResEqual -append
ResEqual		ƒƒ	ResEqual.p.o FStubs.a.o
	Link -w -c 'MPS ' -t MPST ResEqual.p.o FStubs.a.o ∂
		-sn STDIO=Main ∂
		-sn INTENV=Main ∂
		-sn %A5Init=Init ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"Runtime.o ∂
		"{Libraries}"ToolLibs.o ∂
		"{PLibraries}"Paslib.o ∂
		-o ResEqual
ResEqual.p.o	ƒ	ResEqual.p
	Pascal ResEqual.p
FStubs.a.o		ƒ	FStubs.a
	Asm FStubs.a



Memory			ƒ	Memory.DRVW Memory.r
	Rez -rd -c DMOV -t DFIL Memory.r -o Memory
Memory.DRVW 	ƒ	Memory.p.o
	Link -w -rt DRVW=0 ∂
		-sg Memory ∂
		"{Libraries}"DRVRRuntime.o	# This must preceed Memory.p.o ∂
		Memory.p.o ∂
		"{Libraries}"Interface.o ∂
		"{PLibraries}"Paslib.o ∂
		-o Memory.DRVW -c "????" -t "????"
Memory.p.o		ƒ	Memory.p
	Pascal Memory.p



TestPerf	ƒ	TestPerf.p.o
	Link -o TestPerf -t MPST -c 'MPS ' -d ∂
		-l -la > TestPerf.map # produce link map file ∂
		TestPerf.p.o "{Libraries}"PerformLib.o ∂
		"{Libraries}"Interface.o ∂
		"{Libraries}"Runtime.o ∂
		"{PLibraries}"PasLib.o
TestPerf.p.o	ƒ	TestPerf.p
	Pascal TestPerf.p

