/*
	File:		modnames.h

*/


#ifndef	__MODNAMES__
#define	__MODNAMES__

#define	MI_AFU_NAME			"afu"
#define MI_ARP_NAME			"arp"
#define MI_ARPM_NAME		"arpm"
#define MI_COURMUX_NAME		"courmux"
#define	MI_CLONE_NAME		"clone"
#define	MI_DLB_NAME			"dlb"
#define	MI_DLM_NAME			"dlm"
#define	MI_DMODD_NAME		"disdlpi"
#define	MI_DMODT_NAME		"distpi"
#define	MI_DN_NAME			"dn"
#define	MI_DNF_NAME			"dnf"
#define	MI_DRVE_NAME		"drve"
#define MI_ECHO_NAME		"echo"
#define MI_ENXR_NAME		"enxr"
#define MI_RAWIP_NAME		"rawip"
#define MI_RAWIPM_NAME		"rawipm"
#define MI_IP_NAME			"ip"
#define MI_IPM_NAME			"ipm"
#define MI_IPX_NAME			"ipx"
#define MI_LOG_NAME			"log"
#define	MI_MODE_NAME		"mode"
#define	MI_MUX_NAME			"mux"
#define MI_NECHO_NAME		"necho"
#define MI_NPEP_NAME		"npep"
#define MI_NULS_NAME		"nuls"

#define MI_NULZ_NAME		"nulz"
#define	MI_PASS_NAME		"pass"
#define	MI_PIPEMOD_NAME		"pipemod"

#define	MI_SAD_NAME			"sad"
#define	MI_SC_NAME			"sc"
#define	MI_SOCKMOD_NAME		"sockmod"
#define	MI_SPASS_NAME		"spass"
#define	MI_SPX_NAME			"spx"
#define MI_STH_NAME			"mi_sth"
#define MI_TCP_NAME			"tcp"
#define MI_TCPM_NAME		"tcpm"
#define MI_TIMOD_NAME		"timod"
#define MI_TIRDWR_NAME		"tirdwr"
#define	MI_TMOD_NAME		"tmod"
#define	MI_TMUX_NAME		"tmux"
#define	MI_TPIT_NAME		"tpit"
#define	MI_TRSR_NAME		"trsr"
#define	MI_TRXR_NAME		"trxr"
#define MI_UDP_NAME			"udp"
#define MI_UDPM_NAME		"udpm"
#define MI_WELD_NAME		"mi_weld"
#define	MI_XDG_NAME			"xdg"
#define	MI_XECHO_NAME		"xecho"
#define	MI_XF_NAME			"xf"
#define	MI_XFIPX_NAME		"xfipx"
#define	MI_XFXNS_NAME		"xfxns"
#define	MI_XPE_NAME			"xpe"
#define	MI_XS_NAME			"xs"
#define	MI_XTINDG_NAME		"xtindg"
#define	MI_XTINVC_NAME		"xtinvc"
#define	MI_XTM_NAME			"xtm"
#define	MI_XTMIP_NAME		"xtmip"

#define	MI_AFU_DEVICE		"/dev/afu"
#define MI_ARP_DEVICE		"/dev/arp"
#define MI_COURMUX_DEVICE	"/dev/courmux"
#define	MI_CLONE_DEVICE		"/dev/clone"
#define	MI_DLB_DEVICE		"/dev/dlb"
#define	MI_DN_DEVICE		"/dev/dn"
#define	MI_DNF_DEVICE		"/dev/dnf"
#define	MI_DRVE_DEVICE		"/dev/drve"
#define MI_ECHO_DEVICE		"/dev/echo"
#define MI_RAWIP_DEVICE		"/dev/rawip"
#define MI_IP_DEVICE		"/dev/ip"
#define MI_IPX_DEVICE		"/dev/ipx"
#define MI_LOG_DEVICE		"/dev/log"
#define	MI_MUX_DEVICE		"/dev/mux"
#define MI_NECHO_DEVICE		"/dev/necho"
#define MI_NPEP_DEVICE		"/dev/npep"
#define MI_NULS_DEVICE		"/dev/nuls"
#define MI_NULZ_DEVICE		"/dev/nulz"
#define	MI_SAD_DEVICE		"/dev/sad"
#define	MI_SPX_DEVICE		"/dev/spx"
#define MI_TCP_DEVICE		"/dev/tcp"
#define	MI_TMUX_DEVICE		"/dev/tmux"
#define	MI_TMUX0_DEVICE		"/dev/tmux#0"
#define	MI_TPIT_DEVICE		"/dev/tpit"
#define MI_UDP_DEVICE		"/dev/udp"
#define	MI_XDG_DEVICE		"/dev/xdg"
#define	MI_XECHO_DEVICE		"/dev/xecho"
#define	MI_XF_DEVICE		"/dev/xf"
#define	MI_XPE_DEVICE		"/dev/xpe"
#define	MI_XS_DEVICE		"/dev/xs"
#define	MI_XTINDG_DEVICE	"/dev/xtindg"
#define	MI_XTINVC_DEVICE	"/dev/xtinvc"


/* Streamtab entries */
#define	MI_AFU_STREAMTAB	afuinfo
#define MI_ARP_STREAMTAB	arpinfo
#define MI_ARPM_STREAMTAB	arpminfo
#define MI_COURMUX_STREAMTAB	courmuxinfo
#define	MI_CLONE_STREAMTAB	cloneinfo
#define	MI_DLB_STREAMTAB	dlbinfo
#define	MI_DLM_STREAMTAB	dlminfo
#define	MI_DMODD_STREAMTAB	dmoddinfo
#define	MI_DMODT_STREAMTAB	dmodtinfo
#define	MI_DN_STREAMTAB		dninfo
#define	MI_DNF_STREAMTAB	dnfinfo
#define	MI_DRVE_STREAMTAB	drveinfo
#define MI_ECHO_STREAMTAB	echoinfo
#define MI_ENXR_STREAMTAB	enxrinfo
#define MI_IP_STREAMTAB		ipinfo
#define MI_IPM_STREAMTAB	ipminfo
#define MI_IPX_STREAMTAB	ipxinfo
#define MI_LOG_STREAMTAB	loginfo
#define	MI_MODE_STREAMTAB	modeinfo
#define	MI_MUX_STREAMTAB	muxinfo
#define MI_NECHO_STREAMTAB	nechoinfo
#define MI_NPEP_STREAMTAB	npepinfo
#define MI_NULS_STREAMTAB	nulsinfo
#define MI_NULZ_STREAMTAB	nulzinfo
#define	MI_PASS_STREAMTAB	passinfo
#define	MI_PIPEMOD_STREAMTAB	pmodinfo
#define MI_RAWIP_STREAMTAB	rawipinfo
#define MI_RAWIPM_STREAMTAB	rawipminfo
#define	MI_SAD_STREAMTAB	sadinfo
#define	MI_SC_STREAMTAB		scinfo
#define	MI_SOCKMOD_STREAMTAB	sockmodinfo
#define	MI_SPASS_STREAMTAB	spassinfo
#define MI_SPX_STREAMTAB	spxinfo
#define MI_STH_STREAMTAB	mi_sthinfo
#define MI_TCP_STREAMTAB	tcpinfo
#define MI_TCPM_STREAMTAB	tcpminfo
#define MI_TIMOD_STREAMTAB	timodinfo
#define MI_TIRDWR_STREAMTAB	tirdwrinfo
#define	MI_TMOD_STREAMTAB	tmodinfo
#define	MI_TMUX_STREAMTAB	tmuxinfo
#define MI_TPIT_STREAMTAB	tpitinfo
#define MI_TRSR_STREAMTAB	trsrinfo
#define MI_TRXR_STREAMTAB	trxrinfo
#define MI_UDP_STREAMTAB	udpinfo
#define MI_UDPM_STREAMTAB	udpminfo
#define MI_WELD_STREAMTAB	mi_weldinfo
#define	MI_XDG_STREAMTAB	xdginfo
#define	MI_XECHO_STREAMTAB	xechoinfo
#define	MI_XF_STREAMTAB		xfinfo
#define	MI_XFIPX_STREAMTAB	xfipxinfo
#define	MI_XFXNS_STREAMTAB	xfxnsinfo
#define	MI_XPE_STREAMTAB	xpeinfo
#define	MI_XS_STREAMTAB		xsinfo
#define	MI_XTINDG_STREAMTAB	xtindginfo
#define	MI_XTINVC_STREAMTAB	xtinvcinfo
#define	MI_XTM_STREAMTAB	xtminfo
#define	MI_XTMIP_STREAMTAB	xtmipinfo


#define	MI_AFU_DEVFLAG		afudevflag
#define MI_ARP_DEVFLAG		arpdevflag
#define MI_ARPM_DEVFLAG		arpmdevflag
#define MI_COURMUX_DEVFLAG	courmuxdevflag
#define	MI_CLONE_DEVFLAG	clonedevflag
#define	MI_DLB_DEVFLAG		dlbdevflag
#define	MI_DLM_DEVFLAG		dlmdevflag
#define	MI_DMODD_DEVFLAG	dmodddevflag
#define	MI_DMODT_DEVFLAG	dmodtdevflag
#define	MI_DN_DEVFLAG		dndevflag
#define	MI_DNF_DEVFLAG		dnfdevflag
#define	MI_DRVE_DEVFLAG		drvedevflag
#define MI_ECHO_DEVFLAG		echodevflag
#define MI_ENXR_DEVFLAG		enxrdevflag
#define MI_IP_DEVFLAG		ipdevflag
#define MI_IPM_DEVFLAG		ipmdevflag
#define MI_IPX_DEVFLAG		ipxdevflag
#define MI_LOG_DEVFLAG		logdevflag
#define	MI_MODE_DEVFLAG		modedevflag
#define	MI_MUX_DEVFLAG		muxdevflag
#define MI_NECHO_DEVFLAG	nechodevflag
#define MI_NPEP_DEVFLAG		npepdevflag
#define MI_NULS_DEVFLAG		nulsdevflag
#define MI_NULZ_DEVFLAG		nulzdevflag
#define	MI_PASS_DEVFLAG		passdevflag
#define	MI_PIPEMOD_DEVFLAG	pipemoddevflag
#define MI_RAWIP_DEVFLAG	rawipdevflag
#define MI_RAWIPM_DEVFLAG	rawipmdevflag

#define	MI_SAD_DEVFLAG		saddevflag
#define	MI_SC_DEVFLAG		scdevflag
#define	MI_SOCKMOD_DEVFLAG	sockmoddevflag
#define	MI_SPASS_DEVFLAG	spassdevflag
#define MI_SPX_DEVFLAG		spxdevflag
#define MI_TCP_DEVFLAG		tcpdevflag
#define MI_TCPM_DEVFLAG		tcpmdevflag
#define MI_TIMOD_DEVFLAG	timoddevflag
#define MI_TIRDWR_DEVFLAG	tirdwrdevflag
#define	MI_TMOD_DEVFLAG		tmoddevflag
#define	MI_TMUX_DEVFLAG		tmuxdevflag
#define	MI_TPIT_DEVFLAG		tpitdevflag
#define	MI_TRSR_DEVFLAG		trsrdevflag
#define	MI_TRXR_DEVFLAG		trxrdevflag
#define MI_UDP_DEVFLAG		udpdevflag
#define MI_UDPM_DEVFLAG		udpmdevflag
#define	MI_XDG_DEVFLAG		xdgdevflag
#define	MI_XECHO_DEVFLAG	xechodevflag
#define	MI_XF_DEVFLAG		xfdevflag
#define	MI_XFIPX_DEVFLAG	xfipxdevflag
#define	MI_XFXNS_DEVFLAG	xfxnsdevflag
#define	MI_XPE_DEVFLAG		xpedevflag
#define	MI_XS_DEVFLAG		xsdevflag
#define	MI_XTINDG_DEVFLAG	xtindgdevflag
#define	MI_XTINVC_DEVFLAG	xtinvcdevflag
#define	MI_XTM_DEVFLAG		xtmdevflag
#define	MI_XTMIP_DEVFLAG	xtmipdevflag

#define	MI_AFU_SQLVL		SQLVL_QUEUEPAIR
#define MI_ARP_SQLVL		SQLVL_MODULE
#define MI_ARPM_SQLVL		SQLVL_MODULE
#define MI_COURMUX_SQLVL	SQLVL_MODULE
#define	MI_CLONE_SQLVL		SQLVL_MODULE
#define	MI_DLB_SQLVL		SQLVL_QUEUE
#define	MI_DLM_SQLVL		SQLVL_QUEUE
#define	MI_DMODD_SQLVL		SQLVL_QUEUE
#define	MI_DMODT_SQLVL		SQLVL_QUEUE
#define	MI_DN_SQLVL			SQLVL_QUEUE
#define	MI_DNF_SQLVL		SQLVL_QUEUE
#define	MI_DRVE_SQLVL		SQLVL_QUEUEPAIR
#define MI_ECHO_SQLVL		SQLVL_QUEUE
#define MI_ENXR_SQLVL		SQLVL_QUEUE
#define MI_RAWIP_SQLVL		SQLVL_MODULE
#define MI_RAWIPM_SQLVL		SQLVL_MODULE
#define MI_IP_SQLVL			SQLVL_MODULE /* SQLVL_QUEUEPAIR */
#define MI_IPM_SQLVL		SQLVL_MODULE /* SQLVL_QUEUEPAIR */
#define MI_IPX_SQLVL		SQLVL_QUEUE
#define MI_LOG_SQLVL		SQLVL_MODULE
#define	MI_MODE_SQLVL		SQLVL_QUEUEPAIR
#define	MI_MUX_SQLVL		SQLVL_MODULE
#define MI_NECHO_SQLVL		SQLVL_QUEUE

#define MI_NPEP_SQLVL		SQLVL_QUEUE
#define MI_NULS_SQLVL		SQLVL_QUEUE
#define MI_NULZ_SQLVL		SQLVL_QUEUE
#define	MI_PASS_SQLVL		SQLVL_QUEUE
#define	MI_PIPEMOD_SQLVL	SQLVL_QUEUE

#define	MI_SAD_SQLVL		SQLVL_MODULE
#define	MI_SC_SQLVL			SQLVL_QUEUE
#define	MI_SOCKMOD_SQLVL	SQLVL_QUEUEPAIR
#define	MI_SPASS_SQLVL		SQLVL_QUEUE
#define	MI_SPX_SQLVL		SQLVL_QUEUE
#define MI_TCP_SQLVL		SQLVL_MODULE /* SQLVL_QUEUEPAIR */
#define MI_TCPM_SQLVL		SQLVL_MODULE /* SQLVL_QUEUEPAIR */
#define MI_TIMOD_SQLVL		SQLVL_QUEUEPAIR
#define MI_TIRDWR_SQLVL		SQLVL_QUEUE
#define	MI_TMOD_SQLVL		SQLVL_QUEUEPAIR
#define	MI_TMUX_SQLVL		SQLVL_MODULE
#define	MI_TPIT_SQLVL		SQLVL_MODULE
#define	MI_TRSR_SQLVL		SQLVL_MODULE
#define	MI_TRXR_SQLVL		SQLVL_QUEUE
#define MI_UDP_SQLVL		SQLVL_QUEUE
#define MI_UDPM_SQLVL		SQLVL_QUEUE
#define	MI_XDG_SQLVL		SQLVL_QUEUE
#define	MI_XECHO_SQLVL		SQLVL_QUEUE
#define	MI_XF_SQLVL			SQLVL_MODULE
#define	MI_XFIPX_SQLVL		SQLVL_MODULE
#define	MI_XFXNS_SQLVL		SQLVL_MODULE
#define	MI_XPE_SQLVL		SQLVL_QUEUE
#define	MI_XS_SQLVL			SQLVL_QUEUEPAIR
#define	MI_XTINDG_SQLVL		SQLVL_QUEUEPAIR
#define	MI_XTINVC_SQLVL		SQLVL_QUEUEPAIR
#define	MI_XTM_SQLVL		SQLVL_QUEUEPAIR
#define	MI_XTMIP_SQLVL		SQLVL_QUEUEPAIR

#endif	/*_MODNAMES_*/
